add_executable(google_test_libProjectName
	google_test_ProjectName.cpp
)

target_link_libraries(google_test_libProjectName
	PRIVATE libProjectName_obj
)

AddTestResources(google_test_libProjectName resources)

Format(google_test_libProjectName .)
AddGTests(google_test_libProjectName)
EnableCoverage(libProjectName_obj libProjectName_interface)
